springdoc:
  version: 1.0
  api-docs:
    context-path: 
  swagger-ui:
    path: /swagger-ui.html
    url: ${springdoc.api-docs.context-path}/v3/api-docs
    config-url: ${springdoc.api-docs.context-path}/v3/api-docs/swagger-config

server:
  port: ${PORT0:8443}

management:
  server:
    port: ${PORT1:8060}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,httptrace

spring:
  application:
    name: cct-k8s-events-producer
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

stratio:
  vault:
    host: vault.service.eos.internal.domain.com
    auth-type: APP_ROLE
  server:
    security:
      certificates:
        vault: 
          root-ca-bundle-path: /userland/passwords/command-center/ca_bundle
          server-path: /userland/certificates/command-center
          server-crt-name: cct-applications_crt
          server-key-name: cct-applications_key
          keystore-password-path: /userland/passwords/command-center/keystore
        local:
          server-key-path: /tmp/server.key.pk8